stages:
  - lint
  - typecheck
  - test

variables:
  NODE_ENV: test

before_script:
  - npm ci

lint:
  stage: lint
  script:
    - npm run lint
  only:
    - merge_requests

typecheck:
  stage: ts-check
  script:
    - npm run ts-check
  only:
    - merge_requests

